---
 - hosts: test
   become: true
   name: install play1 with java
   tasks:
     - name: install Java on Ubuntu OS
       script: openjdk-install.sh

 - hosts: prod
   become: true
   name: install play2 with mysql server
   tasks: 
     - name: Install MySQL server on Ubuntu OS
       apt: name=mysql-server state=latest
